#!/usr/bin/env sh
#
# ██╗   ██╗ █████╗ ██████╗  █████╗ ██╗
# ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██║
#  ╚████╔╝ ███████║██████╔╝███████║██║
#   ╚██╔╝  ██╔══██║██╔══██╗██╔══██║██║
#    ██║   ██║  ██║██████╔╝██║  ██║██║
#    ╚═╝   ╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝
# A tiling window manager for macOS
# https://github.com/koekeishiya/yabai

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

##############################
# --    Tiling options    -- #
##############################

# set tiling layout, bsp or float
yabai -m config layout bsp

# set default layout for space 1 to float (yabai will leave space 1 alone and not tile it)
 yabai -m config --space 1 layout float

# set new windows to spawn to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# set padding and gap
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# set window auto balance, (off) will not auto balance windows when a new window is created
yabai -m config auto_balance off

# set window stack split ratio
yabai -m config split_ratio 0.50


##############################
# --     Mouse support    -- #
##############################

# set mouse follows focus mode, center mouse on window with focus
yabai -m config mouse_follows_focus on

# set focus follows mouse mode
yabai -m config focus_follows_mouse off

# set mouse interaction modifier key for clicking and dragging with mouse
yabai -m config mouse_modifier alt

# set modifier + left-click drag to move window
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# set drop action, when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m config mouse_drop_action swap


##############################
# -- Window modifications -- #
##############################

# set window origin display, (default) will use the display where the space is located
yabai -m config window_origin_display default

# set floating windows to be always on top (disabled with off)
yabai -m config window_topmost off

# set window shadows (float : only for floating windows)
yabai -m config window_shadow float

# set window opacity
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config window_opacity_duration 0.0

# set window border
yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config active_window_border_color 0xE032CD32
yabai -m config normal_window_border_color 0xE02d74da
yabai -m config insert_feedback_color 0x00010101


##############################
# --      App rules       -- #
##############################

yabai -m rule --add title='Preferences$' manage=off topmost=on
yabai -m rule --add lable="1Password" app="^1Password$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Alfred Preferances$" manage=off
yabai -m rule --add app="^Bartender 5$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Cisco Secure Client$" manage=off
yabai -m rule --add app="^CleanMyMac X$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Docker$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Github Desktop$" manage=off
yabai -m rule --add app="^Microsoft Remote Desktop$" manage=off
yabai -m rule --add app="^System Preferences$" title=".*" manage=off
yabai -m rule --add app="^System Settings$" title=".*" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^Spotify$" manage=off


##############################
# --      Status bar      -- #
##############################
# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
#yabai -m config external_bar main:20:0
# add 20 padding to the top and bottom of all spaces regardless of the display it belongs to
#yabai -m config external_bar all:20:20

echo "yabai configuration loaded.."