#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

yabai -m config external_bar                all:35:0     \
                mouse_follows_focus         on           \
                focus_follows_mouse         off          \
                window_zoom_persist         off          \
                window_placement            second_child \
                window_topmost              off          \
                window_shadow               float        \
                window_origin_display       default      \
                window_opacity              off          \
                window_opacity_duration     0.2          \
                active_window_opacity       1.0          \
                normal_window_opacity       0.95         \
                window_animation_duration   0.3          \
                insert_feedback_color       0xff9dd274   \
                split_ratio                 0.50         \
                auto_balance                off          \
                auto_padding                on           \
                mouse_modifier              alt          \
                mouse_action1               move         \
                mouse_action2               resize       \
                mouse_drop_action           swap         \
                top_padding                 12           \
                bottom_padding              12           \
                left_padding                12           \
                right_padding               12           \
                window_gap                  12

# Exclude apps from being managed:
yabai -m rule --add app="^(1Password|Activity Monitor|App Store|Archive Utility|Bartender 5|Cisco Secure Client|Calculator|CleanMyMac X|Dictionary|Docker|Github Desktop|Microsoft Remote Desktop|Microsoft Teams|Raycast|Software Update|System Preferences|System Settings|zoom.us)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

yabai -m config layout bsp
yabai -m config --space 1 layout float

echo "yabai configuration loaded.."